version: "3"
services:
  db-service:
    container_name: db-service
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init_script.sql:/docker-entrypoint-initdb.d/init_script.sql
      - mysql:/var/lib/mysql
    restart: on-failure
    networks:
      - enet

  filter-fleet:
    container_name: filter-fleet
    image: kritikasingh02/filter-fleet:v1
    ports:
      - "8082:8082"
    environment:
      DB_HOST: db-service
    depends_on:
      - db-service
    volumes:
      - app-data:/wockspace/data
    restart: on-failure
    networks:
      - enet

networks:
  enet:

volumes:
  app-data:
  mysql: